---
- name: create node_exporter system group
  group:
    name: node_exporter
    system: true
    state: present

- name: create node_exporter system user
  user:
    name: node_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: node_exporter
    createhome: false

- name: download node_exporter binary to local folder
  become: false
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch}}.tar.gz"
    checksum: "sha256:{{ node_exporter_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  run_once: true
  delegate_to: localhost
  check_mode: false

- name: unpack node_exporter binaries
  become: false
  unarchive:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch}}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch}}/node_exporter"
  delegate_to: localhost
  check_mode: false

- name: copy node_exporter binaries
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch}}/{{ item }}"
    dest: "{{ node_exporter_binary_install_dir }}/{{ item }}"
    mode: 0770
    owner: node_exporter
    group: node_exporter
  with_items:
    - node_exporter
  notify:
    - "enable and start node_exporter"

- name: create systemd service unit
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: node_exporter
    group: node_exporter
    mode: 0660
  notify:
    - "enable and start node_exporter"
