---
- name: Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key

- name: Grafana apt sources
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    update_cache: true
  register: _update_apt_cache
  until: _update_apt_cache is succeeded
  retries: 5
  delay: 2

- name: install grafana
  apt:
  pkg:
    - grafana
  notify:
    - "enable and start grafana"
