---
- include: update-cache.yml
  become: yes

- include: upgrade-system.yml
  become: yes

- include: install-grafana.yml
  become: yes

- include: configure-grafana.yml
  become: yes

- include: grafana-datasource.yml
  become: yes
