--- 
- name: adding Grafana GPG key
  notify: Grafana GPG key

- name: adding Grafana to apt sources
  notify: Grafana to apt sources

- name: update and upgrade  
  apt: 
    update_cache: yes 
    state: latest 
    upgrade: dist
  become: yes

- name: install grafana
  apt:
    pkg:
      - grafana
  become: yes

- name: enable grafana service
  notify: enable grafana service

- name: start grafana service
  notify: restart grafana service