---
- name: Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
  become: yes

- name: Grafana apt sources
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
  become: yes

- name: update and upgrade
  apt:
    update_cache: yes
    state: latest
    upgrade: dist
  become: yes

- name: install grafana
  apt:
    pkg:
      - grafana
  become: yes

- name: enable grafana
  systemd:
    name: grafana
    enabled: yes
  become: yes

- name: start grafana
  systemd:
    name: grafana
    state: started
  become: yes
