---
# handlers file for roles/node-exporter
- name: enable node_exporter
  listen: "enable and start node_exporter"
  systemd:
    daemon_reload: yes
    name: node_exporter
    enabled: yes
  become: yes

- name: start node_exporter
  listen: "enable and start node_exporter"
  systemd:
    name: node_exporter
    state: started
  become: yes

- name: reload node_exporter
  listen: "enable and start node_exporter"
  systemd:
    name: node_exporter
    state: restarted
  become: yes
