---
- name: remove /etc/nginx/sites-enabled/default
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify:
    - "enable and start nginx service"

- name: create /etc/nginx/conf.d/grafana.conf
  template:
    src: "{{ nginx_grafana_config_file }}"
    dest: "{{ nginx_config_dir }}/grafana.conf"
    force: true
    owner: root
    group: root
  notify:
    - "restart nginx"
  when: ansible_facts['hostname'] == "grafana-vm"

- name: create /etc/nginx/conf.d/prometheus.conf
  template:
    src: "{{ nginx_prometheus_config_file }}"
    dest: "{{ nginx_config_dir }}/prometheus.conf"
    force: true
    owner: root
    group: root
  notify:
    - "restart nginx"
  when: ansible_facts['hostname'] == "prometheus-vm"
