---
# defaults file for roles/node-exporter
node_exporter_version: 1.0.1
__node_exporter_checksum: "3369b76cd2b0ba678b6d618deab320e565c3d93ccb5c2a0d5db51a53857768ae"
node_exporter_binary_local_dir: ""
_node_exporter_binary_install_dir: "/usr/local/bin"
node_exporter_skip_install: false
