---
# configure prometheus
- name: configure prometheus
  become: true
  template:
    src: "{{ prometheus_config_file }}"
    dest: "{{ prometheus_config_dir }}/prometheus.yml"
    force: true
    owner: prometheus
    group: prometheus
    mode: 0660
    validate: "{{ _prometheus_binary_install_dir }}/promtool check config %s"
  notify:
    - "enable and start prometheus"
