--- 
- name: update and upgrade  
  apt: 
    update_cache: yes 
    state: latest 
    upgrade: dist
  become: yes
  
- name: install packages
  apt: 
    pkg:
      - unzip
  become: yes

- name: create /etc/prometheus directory
  file:
    path: /etc/prometheus
    state: directory
  become: yes
  
- name: create /var/lib/prometheus directory
  file:
    path: /var/lib/prometheus
    state: directory
  become: yes

- name: change owner and group for /etc/prometheus
  file:
    path: /etc/prometheus
    owner: prometheus
    group: prometheus
    mode: 0550
  become: yes

- name: change owner and group for /var/lib/prometheus
  file:
    path: /var/lib/prometheus
    owner: prometheus
    group: prometheus
    mode: 0770
  become: yes

- name: download prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.21.0/prometheus-2.21.0.linux-amd64.tar.gz
    dest: /home/prometheus
    checksum: sha256:f1f2eeabbf7822572dce67565dc96ffaa2dd1897dd1d844562552b11123f151a

- name: extract prometheus
  unarchive:
    src: /home/prometheus/prometheus-2.21.0.linux-amd64.tar.gz
    remote_src: yes
    dest: /home/prometheus/
  become: yes

- name: copy prometheus to /usr/local/bin
  copy:
    src: /home/prometheus/prometheus-2.21.0.linux-amd64/prometheus
    remote_src: yes
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    mode: 0550
  become: yes

- name: copy promtool to /usr/local/bin
  copy:
    src: /home/prometheus/prometheus-2.21.0.linux-amd64/promtool
    remote_src: yes
    dest: /usr/local/bin
    owner: prometheus
    group: prometheus
    mode: 0550
  become: yes

- name: copy prometheus-2.21.0.linux-amd64/consoles to /etc/prometheus
  command: cp -r /home/prometheus/prometheus-2.21.0.linux-amd64/consoles /etc/prometheus
  become: yes

- name: copy prometheus-2.21.0.linux-amd64/console_libraries /etc/prometheus
  command: cp -r /home/prometheus/prometheus-2.21.0.linux-amd64/console_libraries /etc/prometheus
  become: yes

- name: change owner and group for /etc/prometheus/consoles
  file:
    dest: /etc/prometheus/consoles
    owner: prometheus
    group: prometheus
    mode: 0770
  become: yes

- name: change owner and group for /etc/prometheus/console_libraries
  file:
    dest: /etc/prometheus/console_libraries
    owner: prometheus
    group: prometheus
    mode: 0770
  become: yes

- name: copy prometheus.service file
  template:
    src: prometheus.service
    dest: /etc/systemd/system/prometheus.service
  become: yes
  
- name: reload daemon
  command: systemctl daemon-reload
  become: yes

- name: copy prometheus config and set permissions
  template: 
    src: prometheus-config.jinja2 
    dest: /etc/prometheus/prometheus.yml
  become: yes

- name: change permission for /etc/prometheus.yml and restart service
  file: 
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0550
  become: yes
  notify: prometheus-service