---
- include: update-system.yml
  become: yes

- include: create-prometheus-user.yml
  become: yes

- include: install-packages.yml
  become: yes

- include: install-prometheus.yml
  become: yes

- include: configure-prometheus.yml
  become: yes
