---
- name: enable grafana
  listen: "enable and start grafana"
  systemd:
    name: grafana-server
    enabled: yes
    state: started

- name: reload grafana
  listen: "enable and start grafana"
  systemd:
    name: grafana-server
    state: restarted
