---
- name: enable grafana
  systemd:
    name: grafana
    enabled: yes
  become: yes

- name: start grafana
  systemd: 
    name: grafana
    state: started
  become: yes

- name: reload grafana
  systemd:
    name: grafana
    state: reloaded
  become: yes