---
- name: enable grafana
  listen: "enable and start grafana"
  systemd:
    name: grafana
    enabled: yes
  become: yes

- name: start grafana
  listen: "enable and start grafana"
  systemd: 
    name: grafana
    state: started
  become: yes

- name: reload grafana
  listen: "enable and start grafana"
  systemd:
    name: grafana
    state: reloaded
  become: yes