---
prometheus_version: 2.21.0
__prometheus_checksum: "f1f2eeabbf7822572dce67565dc96ffaa2dd1897dd1d844562552b11123f151a"
prometheus_binary_local_dir: ""
_prometheus_binary_install_dir: "/usr/local/bin"
prometheus_skip_install: false

prometheus_config_dir: /etc/prometheus
prometheus_db_dir: /var/lib/prometheus

prometheus_web_listen_address: "0.0.0.0:9090"
prometheus_web_external_url: ""

prometheus_storage_retention: "30d"
# Available since Prometheus 2.7.0
# [EXPERIMENTAL] Maximum number of bytes that can be stored for blocks. Units
# supported: KB, MB, GB, TB, PB.
prometheus_storage_retention_size: "0"

prometheus_config_flags_extra: {}
# prometheus_config_flags_extra:
#   storage.tsdb.retention: 15d
#   alertmanager.timeout: 10s

prometheus_config_file: "prometheus-config.yml.j2"

prometheus_targets:
  - "192.168.23.12:9182"
  - "192.168.23.31:9182"
  - "192.168.23.11:9182"
  - "192.168.23.48:9182"
  - "192.168.23.33:9182"
  - "192.168.23.49:9182"
  - "192.168.23.50:9182"
  - "192.168.23.16:9182"
  - "10.0.0.249:9182"
