---
# enable and restart prometheus service
- name: enable prometheus
  listen: "enable and start prometheus"
  systemd:
    daemon_reload: yes
    name: prometheus
    enabled: yes
  become: yes

- name: start prometheus
  listen: "enable and start prometheus"
  systemd:
    daemon_reload: yes
    name: prometheus
    state: started
  become: yes

- name: reload prometheus
  listen: "enable and start prometheus"
  systemd:
    daemon_reload: yes
    name: prometheus
    state: reloaded
  become: yes
