---
# enable and restart prometheus service
- name: enable prometheus
  systemd:
    name: prometheus
    enabled: yes
  become: yes

- name: start prometheus
  systemd:
    name: prometheus
    state: started
  become: yes

- name: reload prometheus
  systemd:
    name: prometheus
    state: reloaded
  become: yes